#!/bin/sh

DAEMON1="/scripts/daemons/devAutoMount"
DAEMON2="/scripts/daemons/mp3main"

test -f ${DAEMON1} || exit 0
test -f ${DAEMON2} || exit 0

startdaemon1(){
  start-stop-daemon -b --start --quiet --exec ${DAEMON1}
}

stopdaemon1(){
  start-stop-daemon --stop --quiet --exec ${DAEMON1}
}

startdaemon2(){
  start-stop-daemon -b --start --quiet --exec ${DAEMON2}
}

stopdaemon2(){
  start-stop-daemon --stop --quiet --exec ${DAEMON2}
}


sleep 5
startdaemon1
startdaemon2
